### PR TITLE
Update Keycloak setup documentation

### PR DESCRIPTION
**Pull request by bcmmbaga**
Add instructions for setting up the netbird with an extra client for accessing the Keycloak user API.

### CODE REVIEW

**Review by pappz — APPROVED** [review]

**Comment by MohammedNoureldin** [comment]
Hi @bcmmbaga,

What was the purpose of this update? It confused me a bit. The previous setup used to work properly for me. Could you please tell a bit more about the benefits of adding a new backend client?

**Comment by bcmmbaga** [comment]
> Hi @bcmmbaga, @pappz,
> 
> What was the purpose of this update? It confused me a bit. The previous setup used to work properly for me. Could you please tell a bit more about the benefits of adding a new backend client?
> 

Hi @MohammedNoureldin. Thanks for reaching out with your concerns. The purpose of the update was to add integration with the Keycloak user API, which allows for more seamless management of user accounts within management server. The addition of a second client for accessing and managing users is a key part of this integration.

You can find the issues that have been addressed by referring to Pull Request. [#746](https://github.com/netbirdio/netbird/pull/746)

**Comment by MohammedNoureldin** [comment]
@bcmmbaga thank you for your reply.

If I understand correct, in case I use LDAP user federation only, I won't need this second client right?

If I am wrong, could you give me a bit more explanation about it. Thank you!

**Comment by MohammedNoureldin** [comment]
Hi @bcmmbaga, may I ask you please if I need to use the suggested configuration for my Keycloak configuration if I use LDAP provider? I am still confused about the PR.

May I ask you please to elaborate a bit about it? I tried to figure it out from the issues, but I got lost.

**Pull request merged**
